POSTS = \
[{'description': 'publico',
  'tags': 'news',
  'url': 'publico.pt',
  'user': 'sicrano'},
 {'description': 'ny times',
  'tags': 'news',
  'url': 'nyt.com',
  'user': 'sicrano'},
 {'description': 'online photographer',
  'tags': 'photography',
  'url': 'theonlinephotographer.com',
  'user': 'sicrano'},
 {'description': 'joel',
  'tags': 'programming',
  'url': 'joelonsoftware.com',
  'user': 'sicrano'},
 {'description': 'django',
  'tags': 'programming',
  'url': 'django.org',
  'user': 'sicrano'},
 {'description': 'codecomplete',
  'tags': 'programming',
  'url': 'codecomplete.com',
  'user': 'sicrano'},
 {'description': 'hacker news',
  'tags': 'programming',
  'url': 'news.ycombinator.com',
  'user': 'sicrano'},
 {'description': 'python',
  'tags': 'programming',
  'url': 'python.org',
  'user': 'sicrano'},
 {'description': 'dn', 'tags': 'news', 'url': 'dn.pt', 'user': 'beltrano'},
 {'description': 'publico',
  'tags': 'news',
  'url': 'publico.pt',
  'user': 'beltrano'},
 {'description': 'ny times',
  'tags': 'news',
  'url': 'nyt.com',
  'user': 'beltrano'},
 {'description': 'joel',
  'tags': 'programming',
  'url': 'joelonsoftware.com',
  'user': 'beltrano'},
 {'description': 'codecomplete',
  'tags': 'programming',
  'url': 'codecomplete.com',
  'user': 'beltrano'},
 {'description': 'hacker news',
  'tags': 'programming',
  'url': 'news.ycombinator.com',
  'user': 'beltrano'},
 {'description': 'python',
  'tags': 'programming',
  'url': 'python.org',
  'user': 'beltrano'},
 {'description': 'ny times',
  'tags': 'news',
  'url': 'nyt.com',
  'user': 'bartok'},
 {'description': 'online photographer',
  'tags': 'photography',
  'url': 'theonlinephotographer.com',
  'user': 'bartok'},
 {'description': 'joel',
  'tags': 'programming',
  'url': 'joelonsoftware.com',
  'user': 'bartok'},
 {'description': 'codecomplete',
  'tags': 'programming',
  'url': 'codecomplete.com',
  'user': 'bartok'},
 {'description': 'hacker news',
  'tags': 'programming',
  'url': 'news.ycombinator.com',
  'user': 'bartok'},
 {'description': 'joel',
  'tags': 'programming',
  'url': 'joelonsoftware.com',
  'user': 'bach'},
 {'description': 'hacker news',
  'tags': 'programming',
  'url': 'news.ycombinator.com',
  'user': 'bach'},
 {'description': 'publico',
  'tags': 'news',
  'url': 'publico.pt',
  'user': 'escher'},
 {'description': 'ny times',
  'tags': 'news',
  'url': 'nyt.com',
  'user': 'escher'},
 {'description': 'hacker news',
  'tags': 'programming',
  'url': 'news.ycombinator.com',
  'user': 'escher'},
 {'description': 'ny times',
  'tags': 'news',
  'url': 'nyt.com',
  'user': 'goedel'},
 {'description': 'online photographer',
  'tags': 'photography',
  'url': 'theonlinephotographer.com',
  'user': 'goedel'},
 {'description': 'online photographer',
  'tags': 'photography',
  'url': 'theonlinephotographer.com',
  'user': 'fulano'},
 {'description': 'joel',
  'tags': 'programming',
  'url': 'joelonsoftware.com',
  'user': 'fulano'},
 {'description': 'django',
  'tags': 'programming',
  'url': 'django.org',
  'user': 'fulano'},
 {'description': 'codecomplete',
  'tags': 'programming',
  'url': 'codecomplete.com',
  'user': 'fulano'},
 {'description': 'hacker news',
  'tags': 'programming',
  'url': 'news.ycombinator.com',
  'user': 'fulano'},
 {'description': 'python',
  'tags': 'programming',
  'url': 'python.org',
  'user': 'fulano'}]
